version: 2.0

orbs:
    node: circleci/node@4.7
    angular: okode/angular@2.0.8

jobs:
    # The test job
    test:
        working_directory: ~/CoctailApp-front
        docker:
            - image: circleci/node:10-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                  name: Show current branch
                  command: echo circleci-project-setup
            # Restore local dependencies from cache
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            # Install project dependencies
            - run:
                  name: Install local dependencies
                  command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
            # Lint the source code
            - run:
                  name: Linting
                  command: npm run lint
            # Test the source code
            - run:
                  name: Testing
                  command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            # End to End test
            - run:
                  name: End to End Test
                  command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
workflows:
    version: 2
    # the test workflow
    test_workflow:
        jobs:
            - deploy:
                  filters:
                      branches:
                          only:
                              - circleci-project-setup